### PR TITLE
Verification function for Crazyflie GUI

### PR DESCRIPTION
**Pull request by AiRuiChen**
Completed the verify function, whose prototype was originally created by not defined in Crazyflie bootloader library. This function reads data back from the Crazyflie firmware and compares them with the original files. I enabled the verify option for flashing function, and now user can select "verify" when flashing to ensure perfect programming. I also added a verification process at the end of "flash" function to report if files are flashed correctly. To improve speeds, I implemented a data batching system. This update eliminates errors at runtime caused by a faulty flashed firmware.

### CODE REVIEW

**Comment by ataffanel** [comment]
Hi, thanks! There is still a flake8 problem: https://travis-ci.org/bitcraze/crazyflie-lib-python/jobs/201343506#L284. Otherwise it looks good so if you can fix flake 8 I will be able to test and merge.

**Comment by krichardsson** [comment]
Hi @AiRuiChen 

I'm not sure what tools you use and how you set up your development environment, but I think the toolbelt is useful to verify the build locally. Take a look at https://wiki.bitcraze.io/projects:dockerbuilderimage:index for more information.

Let us know if you need any help!

- Kristoffer

**Comment by AiRuiChen** [comment]
Hey Kristofeer,

I have actually used the toolbelt to verify the build by running the "tb
build" command. The codes pass the test in locally but can't go through the
check online. I am using MacOS Sierra and I think I've set up the alias
properly.

Do you have any idea on what's wrong?

Thanks,
Eric

**Comment by krichardsson** [comment]
@AiRuiChen, 

not sure why you do not see the errors on your machine. First thing could be to make sure you have the latest toolbelt
```tb update```
I don't think it will make any difference, but anyway.

When I run it locally on your pullrequest (also on OSX, but El Capitan) I get
```
Kristoffers-MacBook-Air-2:crazyflie-lib-python kristoffer$ tb verify
Running build script tools/build/verify in a container based on the bitcraze/builder:12 docker image as user root
autopep8 wrapper.........................................................Failed
hookid: autopep8-wrapper

Files were modified by this hook. Additional output:

Fixing cflib/bootloader/cloader.py
Fixing cflib/bootloader/__init__.py

Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for merge conflicts................................................Passed
Check Xml............................................(no files to check)Skipped
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
Detect Private Key.......................................................Passed
Fix double quoted strings................................................Passed
Fix End of Files.........................................................Passed
Flake8...................................................................Failed
hookid: flake8

cflib/bootloader/__init__.py:825:80: E501 line too long (80 > 79 characters)

Fix requirements.txt.....................................................Passed
Reorder python imports...................................................Passed
Error: verify fail
Traceback (most recent call last):
  File "tools/build/verify", line 9, in <module>
    raise e
subprocess.CalledProcessError: Command '['pre-commit', 'run', '--all-files']' returned non-zero exit status 1
Error: The call 'docker run --rm -u 0 -v /var/run/docker.sock:/var/run/docker.sock -it -v /Users/kristoffer/code/bitcraze/crazyflie-lib-python:/module bitcraze/builder:12 tools/build/verify' failed with error code 1
```

So it looks like the PEP8 checker fixed a few problems (that you need to commit) and that there is one line that is too long that need manual fixing.

Which version of the bitcraze/builder is used when you run on your machine?

**Comment by AiRuiChen** [comment]
@krichardsson ,

I followed the instruction but my toolbelt doesn't even have the "verify" command that you use. 

`Tools in the belt:
  help, -h, --help - Help
  update - Update tool belt to latest version
  version, -V, --version - Display version of the tool belt
  ghrn - Generate release notes from github milestone

Tools in the current module:
  build
  flake8
  image
  test`

This is what I get by running the build command. As you can see, it is passing the flake8 test. 

`tb build __init__.py 
Running build script tools/build/build in a container based on the bitcraze/builder:12 docker image as user root
Flake8 check pass
.........Pulling some.registry:5000/toolbelt:latest
.Pulling registry/toolbelt:latest
.Pulling toolbelt:latest
.Pulling toolbelt:latest
.Pulling some.registry:5000/toolbelt:latest
.Version not available
..my/image:latest - 2016-01-01...
.................................................Running build script script in a container based on the imageName docker image as uid 123
..Running build script script in a container based on the imageName docker image as uid 123
........
----------------------------------------------------------------------
Ran 75 tests in 0.071s

OK
`

What's more, if you check my original code, the length of line 825 is way less than 80. So I'm really confused about how I can manually fix the problem.
I honestly don't know what you mean by the bitcraze/builder version because I verify the code simply by downloading one file and running the "tb build" command on it. If you can help me to fix the style problem (which I believe is really just some formatting), I would really appreciate it. 

Thank you

**Comment by krichardsson** [comment]
@AiRuiChen, 
now I see what is going on! 

The toolbelt has a few built in tools (help, update, version and ghrn), but most of the tools are part of the project it self (it simply looks for scripts in the ./tools/build dir). 
Since this pull request is for crazyflie-lib-python you need to be located in the root of the source tree for the lib. From the list of tools in your comment, it looks like you are located in the toolbelt source directory instead (you don't really need the source for the toolbelt, unless you are interested at looking at it, since it is pulled from dockerhub). The toolbelt only acts on the project you are located in.

So, cd to your crazyflie-lib-python and run the toolbelt there. You should see this
```
Kristoffers-MacBook-Air-2:crazyflie-lib-python kristoffer$ tb
Usage:  tb tool [arguments]
The toolbelt is used to develop, test and build Bitcraze modules. When the toolbelt is called, it will first try to find the tool in the belt, after that it will try the tools in the module if the working directory is the root of a module. Module tools are executed in the context of a docker container based on the module requirements configured in the module.json config file.

Tools in the belt:
  help, -h, --help - Help
  update - Update tool belt to latest version
  version, -V, --version - Display version of the tool belt
  ghrn - Generate release notes from github milestone

Tools in the current module:
  bdist
  build
  test
  verify
```

The bitcraze/builder version is the version of the docker image that is used by the toolbelt to build your project. The toolbelt chooses a builder image based on the configuration of the project you are in (the modul.json file). In you case (when you build the toolbelt source code) it uses bitcraze/builder:12. It all looks good :-)

Just make sure you are in the correct directory and all should be good.

**Pull request closed without merging**
