### PR TITLE
Reorganize examples folder

### LINKED ISSUE #69: Reorganize examples
The directory with example code contains quite a lot of files. It could be improved by reorganizing it using sub folders.

### PR DESCRIPTION
**Pull request by jonasdn**
- Reorganize examples into subdirectories
- Remove unsupported cfbridge example

Closes #69

### CODE REVIEW

**Review by krichardsson — APPROVED** [review]
Looking good!

**Comment by jonasdn** [comment]
@knmcguire could this break any links or references in step-by-step guides?

**Review by ataffanel — COMMENTED** [review]
Looks good.

One question: why is OW separated from "memory"? The "memory" folder contains a mix of physical (eeprom) and virtual (deck mem) memories while OW gets its own folder.

**Comment by jonasdn** [comment]
> Looks good.
> 
> One question: why is OW separated from "memory"? The "memory" folder contains a mix of physical (eeprom) and virtual (deck mem) memories while OW gets its own folder.

Completely arbitrary.

What makes most sense:

- Move all to memory
- Split out into eeprom/deck mem/flash/ow

?

**Comment by knmcguire** [comment]
> @knmcguire could this break any links or references in step-by-step guides?

Nope! They 're in their own folder

The examples that are now put in positioning, isn't that more of autonomy examples? like the highlevel commander and motion commander stuff?

**Comment by ataffanel** [comment]
> Completely arbitrary.
> 
> What makes most sense:
> 
> * Move all to memory
> * Split out into eeprom/deck mem/flash/ow
> 
> ?

There is few enough of them that I would put them all in memory. OW is a bit more special because they are the one to use if you make your own deck, but if you make your own deck you know that your OW chip is a memory so you would find the example.

**Comment by jonasdn** [comment]
> > @knmcguire could this break any links or references in step-by-step guides?
> 
> Nope! They 're in their own folder
> 
> The examples that are now put in positioning, isn't that more of autonomy examples? like the highlevel commander and motion commander stuff?

You may be right! For me the line between positioning and autonomy is not clear. Could you perhaps give  a suggestion of a divide?

**Comment by knmcguire** [comment]
@jonasdn  here is a suggestion:

autonomy
- autonomous_sequence_high_level
- autonomousSequence
- motion_commander_demo
- position_commander_demo

**Comment by jonasdn** [comment]
> @jonasdn here is a suggestion:
> 
> autonomy
> 
> * autonomous_sequence_high_level
> * autonomousSequence
> * motion_commander_demo
> * position_commander_demo

Thanks!

**Review by knmcguire — APPROVED** [review]
Looks good!

**Pull request merged**
