### PR TITLE
Add serial number reader to log

### PR DESCRIPTION
**Pull request by Gadgeteering**
Add crazy radio serial number reader to log

### CODE REVIEW

**Comment by gemenerik** [comment]
Thanks for your PR. Can you[ run pre-commit ](https://github.com/bitcraze/crazyflie-lib-python/blob/master/docs/installation/install.md#pre-commit-hooks-ubuntu)on it?

**Comment by Gadgeteering** [comment]
Pre commit checks

autopep8 wrapper.........................................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for merge conflicts................................................Passed
Check Xml............................................(no files to check)Skipped
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
Detect Private Key.......................................................Passed
Fix double quoted strings................................................Passed
Fix End of Files.........................................................Passed
Flake8...................................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
Reorder python imports...................................................Passed

**Comment by gemenerik** [comment]
Sorry, to clarify. Can you run pre-commit, and then commit and push the changes. There is a pep8 formatting issue with the current PR.

**Comment by Gadgeteering** [comment]
Sorry my mistake ran pre-commit and pushed

**Comment by gemenerik** [comment]
Again thanks so much for your PR!

**Pull request merged**
